name: CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "pushing image to dockerhub..."

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Switch to Current Branch
        run: git checkout main

      - name: Set Env
        run: |
          echo "INFERENCE_SERVICE_IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/spira-model-server:${{github.ref_name}}" >> $GITHUB_ENV
          echo "MLFLOW_SERVER_IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/spira-mlflow-server:${{github.ref_name}}" >> $GITHUB_ENV

      - name: Push Image
        run: bash push-image.sh
      
